// ─────────────────────────────────────────────────────────────────────────────
// Reserved organisation slugs — blocklist for org slug creation.
//
// These slugs are blocked to prevent routing collisions, brand confusion,
// domain term hijacking, and common abuse patterns.
//
// Normalise input (lowercase, trim) before checking against this set.
// ─────────────────────────────────────────────────────────────────────────────

export const RESERVED_SLUGS: ReadonlySet<string> = new Set([
  // ── 1. Application route segments ─────────────────────────────────────────
  // Actual URL path segments used by the API, SPA, and marketing site.
  // Allowing these as org slugs would break routing (e.g. /:orgSlug collision).
  'api',
  'app',
  'auth',
  'account',
  'artifacts',
  'billing',
  'bulk',
  'callback',
  'changelog',
  'check-slug',
  'checkout',
  'claim',
  'copy-from',
  'create-org',
  'dashboard',
  'decision',
  'detach',
  'duplicate',
  'general',
  'health',
  'history',
  'invite',
  'legal',
  'login',
  'logout',
  'members',
  'new',
  'onboarding',
  'open',
  'orgs',
  'playbooks',
  'portal',
  'presign',
  'pricing',
  'privacy',
  'refresh',
  'reorder',
  'result',
  'role',
  'runs',
  'sections',
  'settings',
  'signup',
  'skip',
  'spec-library',
  'specs',
  'start',
  'stripe',
  'subscription',
  'sync',
  'table',
  'terms',
  'url',
  'users',
  'value',
  'webhooks',

  // ── 2. Domain entities & concepts ─────────────────────────────────────────
  // Core domain objects. Blocking these prevents confusion with system entities
  // and protects against social engineering (e.g. "org.nohotfix.io/user").
  'artifact',
  'audit',
  'event',
  'library',
  'membership',
  'migration',
  'org',
  'organisation',
  'organization',
  'playbook',
  'run',
  'section',
  'snapshot',
  'spec',
  'template',
  'user',
  'webhook',

  // ── 3. Roles & permissions ────────────────────────────────────────────────
  // Role names and privilege-related terms that could impersonate authority.
  'admin',
  'administrator',
  'anonymous',
  'guest',
  'manager',
  'member',
  'mod',
  'moderator',
  'operator',
  'owner',
  'private',
  'public',
  'root',
  'staff',
  'sudo',
  'super-admin',
  'superadmin',
  'support',
  'sys-admin',
  'sysadmin',

  // ── 4. Status & state values ──────────────────────────────────────────────
  // Run, spec, and subscription status enums. Blocking avoids confusion
  // in URLs and prevents impersonation of system states.
  'abandoned',
  'active',
  'awaiting-decision',
  'cancelled',
  'expired',
  'failed',
  'go',
  'grace-period',
  'in-progress',
  'no-go',
  'passed',
  'past-due',
  'pending',
  'skipped',
  'trialing',

  // ── 5. Product & brand terms ──────────────────────────────────────────────
  // Brand names, tier names, and lifecycle labels that could mislead users
  // into thinking an org is officially affiliated with the product.
  'alpha',
  'beta',
  'business',
  'canary',
  'corporate',
  'demo',
  'enterprise',
  'free',
  'nightly',
  'official',
  'personal',
  'pilot',
  'plus',
  'premium',
  'preview',
  'pro',
  'production',
  'release',
  'nohotfix',
  'nohotfix-io',
  'staging',
  'starter',
  'team',
  'trial',

  // ── 6. Common web & infrastructure paths ──────────────────────────────────
  // Standard web infrastructure paths that bots, crawlers, and users expect
  // at the root level. Also prevents CDN/proxy routing conflicts.
  'assets',
  'cdn',
  'css',
  'download',
  'downloads',
  'favicon',
  'files',
  'fonts',
  'ftp',
  'images',
  'img',
  'js',
  'mail',
  'manifest',
  'media',
  'robots',
  'scripts',
  'service-worker',
  'sftp',
  'sitemap',
  'ssh',
  'ssl',
  'static',
  'uploads',
  'well-known',
  'www',
  'www1',
  'www2',

  // ── 7. Auth & security paths ──────────────────────────────────────────────
  // Authentication and security-related paths. Many are targeted by scanners
  // and bots; reserving them avoids accidental exposure and confusion.
  'activate',
  'authenticate',
  'authkit',
  'authorize',
  'cas',
  'confirm',
  'deactivate',
  'forgot',
  'forgot-password',
  'magic-auth',
  'magic-link',
  'mfa',
  'oauth',
  'oauth2',
  'otp',
  'password',
  'register',
  'reset',
  'reset-password',
  'saml',
  'session',
  'sessions',
  'sign-in',
  'sign-out',
  'sign-up',
  'signin',
  'signout',
  'sso',
  'token',
  'tokens',
  'two-factor',
  'verify',
  'workos',

  // ── 8. API & system reserved ──────────────────────────────────────────────
  // System-level paths used by health checks, monitoring, debugging,
  // and internal infrastructure. Prevents routing and tooling conflicts.
  'about',
  'cluster',
  'config',
  'configuration',
  'cron',
  'debug',
  'graphql',
  'grpc',
  'healthcheck',
  'healthz',
  'info',
  'internal',
  'jobs',
  'livez',
  'logging',
  'logs',
  'metrics',
  'monitoring',
  'node',
  'ping',
  'pong',
  'queue',
  'readyz',
  'rest',
  'rpc',
  'server',
  'socket',
  'status',
  'sys',
  'system',
  'task',
  'tasks',
  'telemetry',
  'trace',
  'version',
  'websocket',
  'worker',
  'ws',
  'wss',

  // ── 9. Common abuse & confusion vectors ───────────────────────────────────
  // Programming primitives, generic identifiers, and terms that cause
  // confusion in URLs, logs, or database queries.
  'all',
  'anyone',
  'anybody',
  'archive',
  'backup',
  'cache',
  'default',
  'dev',
  'development',
  'everyone',
  'everybody',
  'example',
  'local',
  'localhost',
  'me',
  'mine',
  'my',
  'nan',
  'nil',
  'none',
  'null',
  'self',
  'spam',
  'temp',
  'test',
  'testing',
  'that',
  'this',
  'tmp',
  'trash',
  'true',
  'false',
  'undefined',
  'void',

  // ── 10. Legal, compliance & business pages ────────────────────────────────
  // Pages commonly expected at the root of a domain. Reserving these
  // prevents org slugs from shadowing important informational pages.
  'abuse',
  'affiliates',
  'blog',
  'careers',
  'community',
  'compliance',
  'contact',
  'copyright',
  'discuss',
  'dmca',
  'docs',
  'documentation',
  'faq',
  'feedback',
  'forum',
  'gdpr',
  'help',
  'investors',
  'news',
  'partners',
  'press',
  'report',
  'roadmap',
  'security',
  'terms-of-service',
  'tos',
  'trademark',
  'updates',

  // ── 11. Common vanity & social paths ──────────────────────────────────────
  // Paths used by social platforms and SaaS products. Users may expect
  // these at the root; allowing them as slugs creates confusion.
  'activity',
  'analytics',
  'browse',
  'catalog',
  'chat',
  'connect',
  'connections',
  'directory',
  'discover',
  'explore',
  'export',
  'featured',
  'feed',
  'hot',
  'import',
  'inbox',
  'insights',
  'integrations',
  'latest',
  'marketplace',
  'messages',
  'newest',
  'notifications',
  'popular',
  'profile',
  'profiles',
  'random',
  'reports',
  'search',
  'shop',
  'store',
  'timeline',
  'top',
  'trending',

  // ── 12. Error & utility pages ─────────────────────────────────────────────
  // HTTP error codes and maintenance-related slugs. Prevents org pages
  // from being mistaken for system error or status pages.
  'banned',
  'blocked',
  'coming-soon',
  'deleted',
  'error',
  'forbidden',
  'gone',
  'maintenance',
  'not-found',
  'offline',
  'removed',
  'suspended',
  'unauthorized',
  'unavailable',
  'under-construction',
  '401',
  '403',
  '404',
  '500',
]);
