/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as OnboardingCreateOrgRouteImport } from './routes/onboarding/create-org'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite/$token'
import { Route as AuthenticatedOrgSlugRouteImport } from './routes/_authenticated/$orgSlug'
import { Route as AuthenticatedOrgSlugIndexRouteImport } from './routes/_authenticated/$orgSlug/index'
import { Route as AuthenticatedOrgSlugSettingsRouteRouteImport } from './routes/_authenticated/$orgSlug/settings/route'
import { Route as AuthenticatedOrgSlugSpecLibraryIndexRouteImport } from './routes/_authenticated/$orgSlug/spec-library/index'
import { Route as AuthenticatedOrgSlugSettingsIndexRouteImport } from './routes/_authenticated/$orgSlug/settings/index'
import { Route as AuthenticatedOrgSlugRunsIndexRouteImport } from './routes/_authenticated/$orgSlug/runs/index'
import { Route as AuthenticatedOrgSlugPlaybooksIndexRouteImport } from './routes/_authenticated/$orgSlug/playbooks/index'
import { Route as AuthenticatedOrgSlugHistoryIndexRouteImport } from './routes/_authenticated/$orgSlug/history/index'
import { Route as AuthenticatedOrgSlugSpecLibraryNewRouteImport } from './routes/_authenticated/$orgSlug/spec-library/new'
import { Route as AuthenticatedOrgSlugSpecLibrarySpecIdRouteImport } from './routes/_authenticated/$orgSlug/spec-library/$specId'
import { Route as AuthenticatedOrgSlugSettingsProfileRouteImport } from './routes/_authenticated/$orgSlug/settings/profile'
import { Route as AuthenticatedOrgSlugSettingsMembersRouteImport } from './routes/_authenticated/$orgSlug/settings/members'
import { Route as AuthenticatedOrgSlugSettingsEnvironmentsRouteImport } from './routes/_authenticated/$orgSlug/settings/environments'
import { Route as AuthenticatedOrgSlugSettingsBillingRouteImport } from './routes/_authenticated/$orgSlug/settings/billing'
import { Route as AuthenticatedOrgSlugSettingsAccountRouteImport } from './routes/_authenticated/$orgSlug/settings/account'
import { Route as AuthenticatedOrgSlugRunsStartRouteImport } from './routes/_authenticated/$orgSlug/runs/start'
import { Route as AuthenticatedOrgSlugRunsRunIdRouteImport } from './routes/_authenticated/$orgSlug/runs/$runId'
import { Route as AuthenticatedOrgSlugPlaybooksNewRouteImport } from './routes/_authenticated/$orgSlug/playbooks/new'
import { Route as AuthenticatedOrgSlugPlaybooksPlaybookIdRouteImport } from './routes/_authenticated/$orgSlug/playbooks/$playbookId'
import { Route as AuthenticatedOrgSlugHistoryRunIdRouteImport } from './routes/_authenticated/$orgSlug/history/$runId'
import { Route as AuthenticatedOrgSlugSpecLibrarySpecIdIndexRouteImport } from './routes/_authenticated/$orgSlug/spec-library/$specId.index'
import { Route as AuthenticatedOrgSlugSpecLibrarySpecIdEditRouteImport } from './routes/_authenticated/$orgSlug/spec-library/$specId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const OnboardingCreateOrgRoute = OnboardingCreateOrgRouteImport.update({
  id: '/onboarding/create-org',
  path: '/onboarding/create-org',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgSlugRoute = AuthenticatedOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrgSlugIndexRoute =
  AuthenticatedOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugSettingsRouteRoute =
  AuthenticatedOrgSlugSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugSpecLibraryIndexRoute =
  AuthenticatedOrgSlugSpecLibraryIndexRouteImport.update({
    id: '/spec-library/',
    path: '/spec-library/',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugSettingsIndexRoute =
  AuthenticatedOrgSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgSlugSettingsRouteRoute,
  } as any)
const AuthenticatedOrgSlugRunsIndexRoute =
  AuthenticatedOrgSlugRunsIndexRouteImport.update({
    id: '/runs/',
    path: '/runs/',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugPlaybooksIndexRoute =
  AuthenticatedOrgSlugPlaybooksIndexRouteImport.update({
    id: '/playbooks/',
    path: '/playbooks/',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugHistoryIndexRoute =
  AuthenticatedOrgSlugHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugSpecLibraryNewRoute =
  AuthenticatedOrgSlugSpecLibraryNewRouteImport.update({
    id: '/spec-library/new',
    path: '/spec-library/new',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugSpecLibrarySpecIdRoute =
  AuthenticatedOrgSlugSpecLibrarySpecIdRouteImport.update({
    id: '/spec-library/$specId',
    path: '/spec-library/$specId',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugSettingsProfileRoute =
  AuthenticatedOrgSlugSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedOrgSlugSettingsRouteRoute,
  } as any)
const AuthenticatedOrgSlugSettingsMembersRoute =
  AuthenticatedOrgSlugSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedOrgSlugSettingsRouteRoute,
  } as any)
const AuthenticatedOrgSlugSettingsEnvironmentsRoute =
  AuthenticatedOrgSlugSettingsEnvironmentsRouteImport.update({
    id: '/environments',
    path: '/environments',
    getParentRoute: () => AuthenticatedOrgSlugSettingsRouteRoute,
  } as any)
const AuthenticatedOrgSlugSettingsBillingRoute =
  AuthenticatedOrgSlugSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedOrgSlugSettingsRouteRoute,
  } as any)
const AuthenticatedOrgSlugSettingsAccountRoute =
  AuthenticatedOrgSlugSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedOrgSlugSettingsRouteRoute,
  } as any)
const AuthenticatedOrgSlugRunsStartRoute =
  AuthenticatedOrgSlugRunsStartRouteImport.update({
    id: '/runs/start',
    path: '/runs/start',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugRunsRunIdRoute =
  AuthenticatedOrgSlugRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugPlaybooksNewRoute =
  AuthenticatedOrgSlugPlaybooksNewRouteImport.update({
    id: '/playbooks/new',
    path: '/playbooks/new',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugPlaybooksPlaybookIdRoute =
  AuthenticatedOrgSlugPlaybooksPlaybookIdRouteImport.update({
    id: '/playbooks/$playbookId',
    path: '/playbooks/$playbookId',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugHistoryRunIdRoute =
  AuthenticatedOrgSlugHistoryRunIdRouteImport.update({
    id: '/history/$runId',
    path: '/history/$runId',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugSpecLibrarySpecIdIndexRoute =
  AuthenticatedOrgSlugSpecLibrarySpecIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgSlugSpecLibrarySpecIdRoute,
  } as any)
const AuthenticatedOrgSlugSpecLibrarySpecIdEditRoute =
  AuthenticatedOrgSlugSpecLibrarySpecIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedOrgSlugSpecLibrarySpecIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/$orgSlug': typeof AuthenticatedOrgSlugRouteWithChildren
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/onboarding/create-org': typeof OnboardingCreateOrgRoute
  '/$orgSlug/settings': typeof AuthenticatedOrgSlugSettingsRouteRouteWithChildren
  '/$orgSlug/': typeof AuthenticatedOrgSlugIndexRoute
  '/$orgSlug/history/$runId': typeof AuthenticatedOrgSlugHistoryRunIdRoute
  '/$orgSlug/playbooks/$playbookId': typeof AuthenticatedOrgSlugPlaybooksPlaybookIdRoute
  '/$orgSlug/playbooks/new': typeof AuthenticatedOrgSlugPlaybooksNewRoute
  '/$orgSlug/runs/$runId': typeof AuthenticatedOrgSlugRunsRunIdRoute
  '/$orgSlug/runs/start': typeof AuthenticatedOrgSlugRunsStartRoute
  '/$orgSlug/settings/account': typeof AuthenticatedOrgSlugSettingsAccountRoute
  '/$orgSlug/settings/billing': typeof AuthenticatedOrgSlugSettingsBillingRoute
  '/$orgSlug/settings/environments': typeof AuthenticatedOrgSlugSettingsEnvironmentsRoute
  '/$orgSlug/settings/members': typeof AuthenticatedOrgSlugSettingsMembersRoute
  '/$orgSlug/settings/profile': typeof AuthenticatedOrgSlugSettingsProfileRoute
  '/$orgSlug/spec-library/$specId': typeof AuthenticatedOrgSlugSpecLibrarySpecIdRouteWithChildren
  '/$orgSlug/spec-library/new': typeof AuthenticatedOrgSlugSpecLibraryNewRoute
  '/$orgSlug/history/': typeof AuthenticatedOrgSlugHistoryIndexRoute
  '/$orgSlug/playbooks/': typeof AuthenticatedOrgSlugPlaybooksIndexRoute
  '/$orgSlug/runs/': typeof AuthenticatedOrgSlugRunsIndexRoute
  '/$orgSlug/settings/': typeof AuthenticatedOrgSlugSettingsIndexRoute
  '/$orgSlug/spec-library/': typeof AuthenticatedOrgSlugSpecLibraryIndexRoute
  '/$orgSlug/spec-library/$specId/edit': typeof AuthenticatedOrgSlugSpecLibrarySpecIdEditRoute
  '/$orgSlug/spec-library/$specId/': typeof AuthenticatedOrgSlugSpecLibrarySpecIdIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/onboarding/create-org': typeof OnboardingCreateOrgRoute
  '/': typeof AuthenticatedIndexRoute
  '/$orgSlug': typeof AuthenticatedOrgSlugIndexRoute
  '/$orgSlug/history/$runId': typeof AuthenticatedOrgSlugHistoryRunIdRoute
  '/$orgSlug/playbooks/$playbookId': typeof AuthenticatedOrgSlugPlaybooksPlaybookIdRoute
  '/$orgSlug/playbooks/new': typeof AuthenticatedOrgSlugPlaybooksNewRoute
  '/$orgSlug/runs/$runId': typeof AuthenticatedOrgSlugRunsRunIdRoute
  '/$orgSlug/runs/start': typeof AuthenticatedOrgSlugRunsStartRoute
  '/$orgSlug/settings/account': typeof AuthenticatedOrgSlugSettingsAccountRoute
  '/$orgSlug/settings/billing': typeof AuthenticatedOrgSlugSettingsBillingRoute
  '/$orgSlug/settings/environments': typeof AuthenticatedOrgSlugSettingsEnvironmentsRoute
  '/$orgSlug/settings/members': typeof AuthenticatedOrgSlugSettingsMembersRoute
  '/$orgSlug/settings/profile': typeof AuthenticatedOrgSlugSettingsProfileRoute
  '/$orgSlug/spec-library/new': typeof AuthenticatedOrgSlugSpecLibraryNewRoute
  '/$orgSlug/history': typeof AuthenticatedOrgSlugHistoryIndexRoute
  '/$orgSlug/playbooks': typeof AuthenticatedOrgSlugPlaybooksIndexRoute
  '/$orgSlug/runs': typeof AuthenticatedOrgSlugRunsIndexRoute
  '/$orgSlug/settings': typeof AuthenticatedOrgSlugSettingsIndexRoute
  '/$orgSlug/spec-library': typeof AuthenticatedOrgSlugSpecLibraryIndexRoute
  '/$orgSlug/spec-library/$specId/edit': typeof AuthenticatedOrgSlugSpecLibrarySpecIdEditRoute
  '/$orgSlug/spec-library/$specId': typeof AuthenticatedOrgSlugSpecLibrarySpecIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/$orgSlug': typeof AuthenticatedOrgSlugRouteWithChildren
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/onboarding/create-org': typeof OnboardingCreateOrgRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$orgSlug/settings': typeof AuthenticatedOrgSlugSettingsRouteRouteWithChildren
  '/_authenticated/$orgSlug/': typeof AuthenticatedOrgSlugIndexRoute
  '/_authenticated/$orgSlug/history/$runId': typeof AuthenticatedOrgSlugHistoryRunIdRoute
  '/_authenticated/$orgSlug/playbooks/$playbookId': typeof AuthenticatedOrgSlugPlaybooksPlaybookIdRoute
  '/_authenticated/$orgSlug/playbooks/new': typeof AuthenticatedOrgSlugPlaybooksNewRoute
  '/_authenticated/$orgSlug/runs/$runId': typeof AuthenticatedOrgSlugRunsRunIdRoute
  '/_authenticated/$orgSlug/runs/start': typeof AuthenticatedOrgSlugRunsStartRoute
  '/_authenticated/$orgSlug/settings/account': typeof AuthenticatedOrgSlugSettingsAccountRoute
  '/_authenticated/$orgSlug/settings/billing': typeof AuthenticatedOrgSlugSettingsBillingRoute
  '/_authenticated/$orgSlug/settings/environments': typeof AuthenticatedOrgSlugSettingsEnvironmentsRoute
  '/_authenticated/$orgSlug/settings/members': typeof AuthenticatedOrgSlugSettingsMembersRoute
  '/_authenticated/$orgSlug/settings/profile': typeof AuthenticatedOrgSlugSettingsProfileRoute
  '/_authenticated/$orgSlug/spec-library/$specId': typeof AuthenticatedOrgSlugSpecLibrarySpecIdRouteWithChildren
  '/_authenticated/$orgSlug/spec-library/new': typeof AuthenticatedOrgSlugSpecLibraryNewRoute
  '/_authenticated/$orgSlug/history/': typeof AuthenticatedOrgSlugHistoryIndexRoute
  '/_authenticated/$orgSlug/playbooks/': typeof AuthenticatedOrgSlugPlaybooksIndexRoute
  '/_authenticated/$orgSlug/runs/': typeof AuthenticatedOrgSlugRunsIndexRoute
  '/_authenticated/$orgSlug/settings/': typeof AuthenticatedOrgSlugSettingsIndexRoute
  '/_authenticated/$orgSlug/spec-library/': typeof AuthenticatedOrgSlugSpecLibraryIndexRoute
  '/_authenticated/$orgSlug/spec-library/$specId/edit': typeof AuthenticatedOrgSlugSpecLibrarySpecIdEditRoute
  '/_authenticated/$orgSlug/spec-library/$specId/': typeof AuthenticatedOrgSlugSpecLibrarySpecIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/accept-invite/$token'
    | '/onboarding/create-org'
    | '/$orgSlug/settings'
    | '/$orgSlug/'
    | '/$orgSlug/history/$runId'
    | '/$orgSlug/playbooks/$playbookId'
    | '/$orgSlug/playbooks/new'
    | '/$orgSlug/runs/$runId'
    | '/$orgSlug/runs/start'
    | '/$orgSlug/settings/account'
    | '/$orgSlug/settings/billing'
    | '/$orgSlug/settings/environments'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/spec-library/$specId'
    | '/$orgSlug/spec-library/new'
    | '/$orgSlug/history/'
    | '/$orgSlug/playbooks/'
    | '/$orgSlug/runs/'
    | '/$orgSlug/settings/'
    | '/$orgSlug/spec-library/'
    | '/$orgSlug/spec-library/$specId/edit'
    | '/$orgSlug/spec-library/$specId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite/$token'
    | '/onboarding/create-org'
    | '/'
    | '/$orgSlug'
    | '/$orgSlug/history/$runId'
    | '/$orgSlug/playbooks/$playbookId'
    | '/$orgSlug/playbooks/new'
    | '/$orgSlug/runs/$runId'
    | '/$orgSlug/runs/start'
    | '/$orgSlug/settings/account'
    | '/$orgSlug/settings/billing'
    | '/$orgSlug/settings/environments'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/spec-library/new'
    | '/$orgSlug/history'
    | '/$orgSlug/playbooks'
    | '/$orgSlug/runs'
    | '/$orgSlug/settings'
    | '/$orgSlug/spec-library'
    | '/$orgSlug/spec-library/$specId/edit'
    | '/$orgSlug/spec-library/$specId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/$orgSlug'
    | '/accept-invite/$token'
    | '/onboarding/create-org'
    | '/_authenticated/'
    | '/_authenticated/$orgSlug/settings'
    | '/_authenticated/$orgSlug/'
    | '/_authenticated/$orgSlug/history/$runId'
    | '/_authenticated/$orgSlug/playbooks/$playbookId'
    | '/_authenticated/$orgSlug/playbooks/new'
    | '/_authenticated/$orgSlug/runs/$runId'
    | '/_authenticated/$orgSlug/runs/start'
    | '/_authenticated/$orgSlug/settings/account'
    | '/_authenticated/$orgSlug/settings/billing'
    | '/_authenticated/$orgSlug/settings/environments'
    | '/_authenticated/$orgSlug/settings/members'
    | '/_authenticated/$orgSlug/settings/profile'
    | '/_authenticated/$orgSlug/spec-library/$specId'
    | '/_authenticated/$orgSlug/spec-library/new'
    | '/_authenticated/$orgSlug/history/'
    | '/_authenticated/$orgSlug/playbooks/'
    | '/_authenticated/$orgSlug/runs/'
    | '/_authenticated/$orgSlug/settings/'
    | '/_authenticated/$orgSlug/spec-library/'
    | '/_authenticated/$orgSlug/spec-library/$specId/edit'
    | '/_authenticated/$orgSlug/spec-library/$specId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  OnboardingCreateOrgRoute: typeof OnboardingCreateOrgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/onboarding/create-org': {
      id: '/onboarding/create-org'
      path: '/onboarding/create-org'
      fullPath: '/onboarding/create-org'
      preLoaderRoute: typeof OnboardingCreateOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$orgSlug': {
      id: '/_authenticated/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof AuthenticatedOrgSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$orgSlug/': {
      id: '/_authenticated/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof AuthenticatedOrgSlugIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/settings': {
      id: '/_authenticated/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof AuthenticatedOrgSlugSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/spec-library/': {
      id: '/_authenticated/$orgSlug/spec-library/'
      path: '/spec-library'
      fullPath: '/$orgSlug/spec-library/'
      preLoaderRoute: typeof AuthenticatedOrgSlugSpecLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/settings/': {
      id: '/_authenticated/$orgSlug/settings/'
      path: '/'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof AuthenticatedOrgSlugSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugSettingsRouteRoute
    }
    '/_authenticated/$orgSlug/runs/': {
      id: '/_authenticated/$orgSlug/runs/'
      path: '/runs'
      fullPath: '/$orgSlug/runs/'
      preLoaderRoute: typeof AuthenticatedOrgSlugRunsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/playbooks/': {
      id: '/_authenticated/$orgSlug/playbooks/'
      path: '/playbooks'
      fullPath: '/$orgSlug/playbooks/'
      preLoaderRoute: typeof AuthenticatedOrgSlugPlaybooksIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/history/': {
      id: '/_authenticated/$orgSlug/history/'
      path: '/history'
      fullPath: '/$orgSlug/history/'
      preLoaderRoute: typeof AuthenticatedOrgSlugHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/spec-library/new': {
      id: '/_authenticated/$orgSlug/spec-library/new'
      path: '/spec-library/new'
      fullPath: '/$orgSlug/spec-library/new'
      preLoaderRoute: typeof AuthenticatedOrgSlugSpecLibraryNewRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/spec-library/$specId': {
      id: '/_authenticated/$orgSlug/spec-library/$specId'
      path: '/spec-library/$specId'
      fullPath: '/$orgSlug/spec-library/$specId'
      preLoaderRoute: typeof AuthenticatedOrgSlugSpecLibrarySpecIdRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/settings/profile': {
      id: '/_authenticated/$orgSlug/settings/profile'
      path: '/profile'
      fullPath: '/$orgSlug/settings/profile'
      preLoaderRoute: typeof AuthenticatedOrgSlugSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedOrgSlugSettingsRouteRoute
    }
    '/_authenticated/$orgSlug/settings/members': {
      id: '/_authenticated/$orgSlug/settings/members'
      path: '/members'
      fullPath: '/$orgSlug/settings/members'
      preLoaderRoute: typeof AuthenticatedOrgSlugSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedOrgSlugSettingsRouteRoute
    }
    '/_authenticated/$orgSlug/settings/environments': {
      id: '/_authenticated/$orgSlug/settings/environments'
      path: '/environments'
      fullPath: '/$orgSlug/settings/environments'
      preLoaderRoute: typeof AuthenticatedOrgSlugSettingsEnvironmentsRouteImport
      parentRoute: typeof AuthenticatedOrgSlugSettingsRouteRoute
    }
    '/_authenticated/$orgSlug/settings/billing': {
      id: '/_authenticated/$orgSlug/settings/billing'
      path: '/billing'
      fullPath: '/$orgSlug/settings/billing'
      preLoaderRoute: typeof AuthenticatedOrgSlugSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedOrgSlugSettingsRouteRoute
    }
    '/_authenticated/$orgSlug/settings/account': {
      id: '/_authenticated/$orgSlug/settings/account'
      path: '/account'
      fullPath: '/$orgSlug/settings/account'
      preLoaderRoute: typeof AuthenticatedOrgSlugSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedOrgSlugSettingsRouteRoute
    }
    '/_authenticated/$orgSlug/runs/start': {
      id: '/_authenticated/$orgSlug/runs/start'
      path: '/runs/start'
      fullPath: '/$orgSlug/runs/start'
      preLoaderRoute: typeof AuthenticatedOrgSlugRunsStartRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/runs/$runId': {
      id: '/_authenticated/$orgSlug/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/$orgSlug/runs/$runId'
      preLoaderRoute: typeof AuthenticatedOrgSlugRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/playbooks/new': {
      id: '/_authenticated/$orgSlug/playbooks/new'
      path: '/playbooks/new'
      fullPath: '/$orgSlug/playbooks/new'
      preLoaderRoute: typeof AuthenticatedOrgSlugPlaybooksNewRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/playbooks/$playbookId': {
      id: '/_authenticated/$orgSlug/playbooks/$playbookId'
      path: '/playbooks/$playbookId'
      fullPath: '/$orgSlug/playbooks/$playbookId'
      preLoaderRoute: typeof AuthenticatedOrgSlugPlaybooksPlaybookIdRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/history/$runId': {
      id: '/_authenticated/$orgSlug/history/$runId'
      path: '/history/$runId'
      fullPath: '/$orgSlug/history/$runId'
      preLoaderRoute: typeof AuthenticatedOrgSlugHistoryRunIdRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/spec-library/$specId/': {
      id: '/_authenticated/$orgSlug/spec-library/$specId/'
      path: '/'
      fullPath: '/$orgSlug/spec-library/$specId/'
      preLoaderRoute: typeof AuthenticatedOrgSlugSpecLibrarySpecIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugSpecLibrarySpecIdRoute
    }
    '/_authenticated/$orgSlug/spec-library/$specId/edit': {
      id: '/_authenticated/$orgSlug/spec-library/$specId/edit'
      path: '/edit'
      fullPath: '/$orgSlug/spec-library/$specId/edit'
      preLoaderRoute: typeof AuthenticatedOrgSlugSpecLibrarySpecIdEditRouteImport
      parentRoute: typeof AuthenticatedOrgSlugSpecLibrarySpecIdRoute
    }
  }
}

interface AuthenticatedOrgSlugSettingsRouteRouteChildren {
  AuthenticatedOrgSlugSettingsAccountRoute: typeof AuthenticatedOrgSlugSettingsAccountRoute
  AuthenticatedOrgSlugSettingsBillingRoute: typeof AuthenticatedOrgSlugSettingsBillingRoute
  AuthenticatedOrgSlugSettingsEnvironmentsRoute: typeof AuthenticatedOrgSlugSettingsEnvironmentsRoute
  AuthenticatedOrgSlugSettingsMembersRoute: typeof AuthenticatedOrgSlugSettingsMembersRoute
  AuthenticatedOrgSlugSettingsProfileRoute: typeof AuthenticatedOrgSlugSettingsProfileRoute
  AuthenticatedOrgSlugSettingsIndexRoute: typeof AuthenticatedOrgSlugSettingsIndexRoute
}

const AuthenticatedOrgSlugSettingsRouteRouteChildren: AuthenticatedOrgSlugSettingsRouteRouteChildren =
  {
    AuthenticatedOrgSlugSettingsAccountRoute:
      AuthenticatedOrgSlugSettingsAccountRoute,
    AuthenticatedOrgSlugSettingsBillingRoute:
      AuthenticatedOrgSlugSettingsBillingRoute,
    AuthenticatedOrgSlugSettingsEnvironmentsRoute:
      AuthenticatedOrgSlugSettingsEnvironmentsRoute,
    AuthenticatedOrgSlugSettingsMembersRoute:
      AuthenticatedOrgSlugSettingsMembersRoute,
    AuthenticatedOrgSlugSettingsProfileRoute:
      AuthenticatedOrgSlugSettingsProfileRoute,
    AuthenticatedOrgSlugSettingsIndexRoute:
      AuthenticatedOrgSlugSettingsIndexRoute,
  }

const AuthenticatedOrgSlugSettingsRouteRouteWithChildren =
  AuthenticatedOrgSlugSettingsRouteRoute._addFileChildren(
    AuthenticatedOrgSlugSettingsRouteRouteChildren,
  )

interface AuthenticatedOrgSlugSpecLibrarySpecIdRouteChildren {
  AuthenticatedOrgSlugSpecLibrarySpecIdEditRoute: typeof AuthenticatedOrgSlugSpecLibrarySpecIdEditRoute
  AuthenticatedOrgSlugSpecLibrarySpecIdIndexRoute: typeof AuthenticatedOrgSlugSpecLibrarySpecIdIndexRoute
}

const AuthenticatedOrgSlugSpecLibrarySpecIdRouteChildren: AuthenticatedOrgSlugSpecLibrarySpecIdRouteChildren =
  {
    AuthenticatedOrgSlugSpecLibrarySpecIdEditRoute:
      AuthenticatedOrgSlugSpecLibrarySpecIdEditRoute,
    AuthenticatedOrgSlugSpecLibrarySpecIdIndexRoute:
      AuthenticatedOrgSlugSpecLibrarySpecIdIndexRoute,
  }

const AuthenticatedOrgSlugSpecLibrarySpecIdRouteWithChildren =
  AuthenticatedOrgSlugSpecLibrarySpecIdRoute._addFileChildren(
    AuthenticatedOrgSlugSpecLibrarySpecIdRouteChildren,
  )

interface AuthenticatedOrgSlugRouteChildren {
  AuthenticatedOrgSlugSettingsRouteRoute: typeof AuthenticatedOrgSlugSettingsRouteRouteWithChildren
  AuthenticatedOrgSlugIndexRoute: typeof AuthenticatedOrgSlugIndexRoute
  AuthenticatedOrgSlugHistoryRunIdRoute: typeof AuthenticatedOrgSlugHistoryRunIdRoute
  AuthenticatedOrgSlugPlaybooksPlaybookIdRoute: typeof AuthenticatedOrgSlugPlaybooksPlaybookIdRoute
  AuthenticatedOrgSlugPlaybooksNewRoute: typeof AuthenticatedOrgSlugPlaybooksNewRoute
  AuthenticatedOrgSlugRunsRunIdRoute: typeof AuthenticatedOrgSlugRunsRunIdRoute
  AuthenticatedOrgSlugRunsStartRoute: typeof AuthenticatedOrgSlugRunsStartRoute
  AuthenticatedOrgSlugSpecLibrarySpecIdRoute: typeof AuthenticatedOrgSlugSpecLibrarySpecIdRouteWithChildren
  AuthenticatedOrgSlugSpecLibraryNewRoute: typeof AuthenticatedOrgSlugSpecLibraryNewRoute
  AuthenticatedOrgSlugHistoryIndexRoute: typeof AuthenticatedOrgSlugHistoryIndexRoute
  AuthenticatedOrgSlugPlaybooksIndexRoute: typeof AuthenticatedOrgSlugPlaybooksIndexRoute
  AuthenticatedOrgSlugRunsIndexRoute: typeof AuthenticatedOrgSlugRunsIndexRoute
  AuthenticatedOrgSlugSpecLibraryIndexRoute: typeof AuthenticatedOrgSlugSpecLibraryIndexRoute
}

const AuthenticatedOrgSlugRouteChildren: AuthenticatedOrgSlugRouteChildren = {
  AuthenticatedOrgSlugSettingsRouteRoute:
    AuthenticatedOrgSlugSettingsRouteRouteWithChildren,
  AuthenticatedOrgSlugIndexRoute: AuthenticatedOrgSlugIndexRoute,
  AuthenticatedOrgSlugHistoryRunIdRoute: AuthenticatedOrgSlugHistoryRunIdRoute,
  AuthenticatedOrgSlugPlaybooksPlaybookIdRoute:
    AuthenticatedOrgSlugPlaybooksPlaybookIdRoute,
  AuthenticatedOrgSlugPlaybooksNewRoute: AuthenticatedOrgSlugPlaybooksNewRoute,
  AuthenticatedOrgSlugRunsRunIdRoute: AuthenticatedOrgSlugRunsRunIdRoute,
  AuthenticatedOrgSlugRunsStartRoute: AuthenticatedOrgSlugRunsStartRoute,
  AuthenticatedOrgSlugSpecLibrarySpecIdRoute:
    AuthenticatedOrgSlugSpecLibrarySpecIdRouteWithChildren,
  AuthenticatedOrgSlugSpecLibraryNewRoute:
    AuthenticatedOrgSlugSpecLibraryNewRoute,
  AuthenticatedOrgSlugHistoryIndexRoute: AuthenticatedOrgSlugHistoryIndexRoute,
  AuthenticatedOrgSlugPlaybooksIndexRoute:
    AuthenticatedOrgSlugPlaybooksIndexRoute,
  AuthenticatedOrgSlugRunsIndexRoute: AuthenticatedOrgSlugRunsIndexRoute,
  AuthenticatedOrgSlugSpecLibraryIndexRoute:
    AuthenticatedOrgSlugSpecLibraryIndexRoute,
}

const AuthenticatedOrgSlugRouteWithChildren =
  AuthenticatedOrgSlugRoute._addFileChildren(AuthenticatedOrgSlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedOrgSlugRoute: typeof AuthenticatedOrgSlugRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOrgSlugRoute: AuthenticatedOrgSlugRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  OnboardingCreateOrgRoute: OnboardingCreateOrgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
